development:
  adapter: postgresql
  encoding: utf8
  database: twitter_development
  username: postgres
  password: 143614
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: twitter_test
  username: postgres
  password: 143614
  host: localhost